name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytest colorama
          pip install -e .

      - name: Run tests
        run: pytest tests/

      - name: Build Citadel Server ({{ matrix.os }})
        run: |
          pyinstaller --onefile main.py --name citadel_${{ matrix.os }}

      - name: Build Phantom Agent ({{ matrix.os }})
        run: |
          pyinstaller --onefile citadel/agent/phantom.py --name phantom_${{ matrix.os }} --collect-all citadel.protocol

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: |
            dist/*
          prerelease: false
